name: healthy_tracker
description: "A new Flutter project."
publish_to: "none"

version: 1.5.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.3.1
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter_bloc: ^8.1.5
  flutter_offline: ^3.0.1
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  sign_in_button: ^4.0.1
  flutter_facebook_auth: ^7.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
